Issue #1756: Added data to datepicker for preselecting pending time
RotherOSS/otobo pull request #1832
Opened 2022-07-04 13:36 UTC by stefanhaerter

2023-02-09 16:03 UTC, svenoe reviewed
Please set DiffTime to 0 if old until time was present.
Please use % for PendingTimeSettings.
Please add SysConfig-Setting "Remember last pending time".
Please check whether RealTimeTillNotUsed is later than now.

2023-02-10 06:07 UTC, stefanhaerter commented
RealTillTimeNotUsed only appears within the code I added within this PR in the whole file.

Note for Development: Check whether RestorePendingInformation retrieves some relevant information from walking through the history.

2023-02-10 12:45 UTC, svenoe commented on Kernel/Config/Files/XML/Ticket.xml
> +    <Setting Name="Ticket::Frontend::AgentTicketActionCommon###RememberLastPendingTime" Required="0" Valid="1">
###RestorePendingTime

2023-02-10 12:55 UTC, svenoe requested changes

2023-02-10 12:55 UTC, svenoe commented on Kernel/Config/Files/XML/Ticket.xml
> +        <Navigation>Frontend::Agent::View::TicketActionCommon</Navigation>
see PendingDiffTime

2023-02-10 12:55 UTC, svenoe commented on Kernel/Config/Files/XML/Ticket.xml
> +        <Description Translatable="1">Defines if in input masks based on AgentTicketActionCommon a potentially set pending time should be prefilled if it is later than now.</Description>
Restore last pending time in input masks based on AgentTicketActionCommon, if pending state is set.

2023-10-06 12:29 UTC, stefanhaerter commented
See https://github.com/RotherOSS/otobo/issues/1756#issuecomment-1750572649

2024-09-16 06:43 UTC, merged