Issue #1946: Add check for customer user password
RotherOSS/otobo pull request #1947
Opened 2022-09-19 10:40 UTC by stefanhaerter

2022-09-19 11:33 UTC, svenoe requested changes
This would mean that passwords cannot be deleted.

2022-09-19 11:40 UTC, stefanhaerter commented
Ah, I forgot this case. if (defined ...) should fix this, right?

2023-02-09 15:37 UTC, svenoe commented on Kernel/Modules/AdminCustomerUser.pm
>              if ( $CurrentUserData{UserPassword} ne $GetParam{UserPassword} ) {
Please don't change the variable, instead use:
if ( ( undef // "123" ) eq "123" ) {print "klappt\n"}

2023-10-05 09:39 UTC, stefanhaerter commented
Closing in favor of #2554

2023-10-05 09:39 UTC, closed without merging